services:
  - type: web
    name: rank-fight
    runtime: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
